const my_data = [
  {
    title: "Apple iPhone 15",
    description:"The Apple iPhone is a sleek, high-performance smartphone known for its premium design and user-friendly interface. It runs on iOS, offering seamless integration with other Apple devices and services. iPhones feature powerful processors, advanced camera systems, and cutting-edge security like Face ID. They support a vast ecosystem of apps, making them ideal for work, entertainment, and creativity. With regular software updates, Apple ensures long-term performance and enhanced user experience.",
    image:"/Image/Phone_image/image_1_iPhone.jpg",
    old_price:1350000,
    new_price: 120000,
  },  
  {
    title: "Laptop core i5 12th Gen",
    description:"A laptop with Intel Core i5 12th Gen processor offers a perfect balance of performance and efficiency. It features hybrid architecture with performance and efficiency cores for multitasking and productivity. Ideal for office work, casual gaming, and media editing, it ensures smooth everyday use. Most models include fast SSD storage, Full HD display, and modern connectivity options like Wi-Fi 6. This processor delivers reliable performance for students, professionals, and general users alike.",
    image:"/Image/card_img/laptop_card.jpg",
    old_price: 74999,
    new_price: 64999,
  },
  {
    title: "Apple iPad 10th Gen | 256GB |",
    description:"The Apple iPad 10th Generation with 256GB storage offers a sleek design and powerful performance. It features a 10.9-inch Liquid Retina display, ideal for streaming, drawing, and multitasking. Powered by the A14 Bionic chip, it handles apps, games, and productivity tasks smoothly. With 256GB of storage, there's ample space for files, apps, and media. Compatible with Apple Pencil and Magic Keyboard, it's perfect for work, study, and creativity.",
    image:"/Image/card_img/tablet_card.jpg",
    old_price: 42999,
    new_price: 34999,
  },
  {
    title: "P18 Pro Drone with 4K HD Camera",
    description:"A compact, foldable quadcopter with dual 4K HD front and bottom cameras, offering real-time Wi-Fi FPV streaming and smooth electric-angle adjustment—perfect for dynamic aerial shots. Equipped with brushless motors and intelligent 540° obstacle-avoidance sensors, it ensures stable, safe, and quiet flight—ideal for both beginners and pros. ",
    image:"/Image/card_img/drone_card.jpg",
    old_price: 85999,
    new_price: 72599,
  },
  {
    title: "XIAOMI by Mi 32 inch HD",
    description:"A 32-inch (80 cm) HD-Ready LED display with 1366x768 resolution, 178° wide viewing angle, and a 60 Hz refresh rate for everyday viewing. Runs on Android TV (PatchWall UI) tailored for India, featuring regional language support and content discovery via curated OTT integration. Offers ample connectivity with 3 HDMI (one ARC), 2 USB 2.0 ports, Ethernet, AV input, headphone jack, and single-band Wi-Fi (2.4 GHz)",
    image:"/Image/card_img/tv_card.jpg",
    old_price: 21599,
    new_price: 18599,
  },
  {
    title: "Sony Bluetooth Speaker",
    description:"A compact and rugged portable speaker featuring Sony's Extra Bass technology and Sound Diffusion Processor for deep, punchy sound despite its small size. Offers up to 16 hours of battery life, with a convenient smartphone battery-level indicator. Supports Google Fast Pair on Android devices for one-tap quick Bluetooth connection.",
    image:"/Image/card_img/speaker_card.jpg",
    old_price:2599,
    new_price: 1999,
  },
  {
    title: "New Smart Android Watch",
    description:"Sleek, modern design featuring a full-color touchscreen and interchangeable straps for both sporty and elegant looks. Runs on Wear OS (or Android-compatible system) with access to Google apps, customizable watch faces, and third-party apps. Tracks health metrics like heart rate, blood oxygen (SpO₂), sleep patterns, plus built-in sensors for steps and calories.",
    image:"/Image/card_img/watch_card.jpg",
    old_price:3299,
    new_price:2499,
  },
  {
    title: "NEW LIGHTING Ceiling Light ",
    description:"A compact LED recessed ceiling light (5-10 W) designed for modern interiors—ideal as deep junction/downlights for homes or offices. Built from durable PVC or polycarbonate and finished in white, it offers sleek minimalism and ease of installation. Provides high brightness (≈100-lm/W) with efficient LED output, low power consumption, and built-in surge protection (up to 4 kV).",
    image:"/Image/card_img/led_card.jpg",
    old_price:1999,
    new_price:1199,
  },
  {
    title: "This is a New Freeze ",
    description:"A dedicated refrigeration appliance—either chest, upright, drawer, or integrated—designed to maintain sub-zero temperatures for preserving food long-term. Many kitchen freezers feature frost-free (No-Frost) technology, eliminating manual defrosting work, though manually defrosted models are typically more energy-efficient.",
    image:"/Image/card_img/freeze.jpg",
    old_price:15599,
    new_price:12999,
  },
  {
    title: "Zebronics Bluetooth Headphone ",
    description:"Zebronics Bluetooth headphones offer long battery life, with models like the Zeb-Aeon providing up to 110 hours of playback on a single charge. They feature Active Noise Cancellation (ANC) and Environmental Noise Cancellation (ENC) for immersive audio experiences. Foldable and lightweight designs ensure portability and comfort for extended use.",
    image:"/Image/Headphone/head_5_zebroinc.jpg",
    old_price:3499,
    new_price:2149,
  },
  {
  title: "OnePlus Nord CE 3 Lite 5G ",
  description:"The OnePlus Nord CE 3 Lite 5G packs a spacious 6.72″ Full HD+ (2400x1080) LCD with a silky-smooth 120 Hz refresh rate and a 240 Hz touch response for gaming and media use. It's powered by a Snapdragon 695 5G chip, coupled with 8 GB RAM plus up to 256 GB UFS 2.2 storage and a micro-SD slot (up to 1 TB), ensuring snappy day-to-day performance. ",
  image:"/Image/Phone_image/image_3_OnePlus.jpg",
  old_price:42599,
  new_price:34599,
  },
  {
  title: "Noise Smart Android Watch",
  description:"The Noise Smart Android Watch offers a sharp 1.32'-1.85' TFT/AMOLED display (up to 550 nits) for crisp, sunlight-readable visuals. With built-in Bluetooth calling and Tru-Sync™ stability, you can dial, answer calls, and access contacts directly from your wrist. It supports a full health suite—24x7 heart rate monitoring, SpO₂ tracking, sleep analysis, stress monitoring—and typically includes 60-100 sport modes.",
  image:"/Image/watch_image/watch_3.jpg",
  old_price:3199,
  new_price:2149,
  },
  {
  title: "Zebronic Ear Phone",
  description:"Features a sturdy 1.2 m textured cable and durable 3.5 mm L-shaped connector for reliable, tangle-free use. Loud and punchy sound from large drivers (10-14 mm neodymium or dynamic units), delivering balanced audio from deep bass to clear mids. Built-in inline microphone with volume and media controls lets you take calls and manage playback hands-free ",
  image:"/Image/Headphone/head_3_zebronic.jpg",
  old_price:1799,
  new_price:1199,
  },
  {
  title: "Samsung Galaxy Book 4",
  description:"Sleek, lightweight (≈1.55 kg) all-metal laptop with a 15.6″ FHD anti-glare display—sturdy yet portable for daily use. Powered by 13th-gen Intel Core (i5 or i7 U-series), 8-16 GB LPDDR4X RAM, and up to 512 GB PCIe SSD, offering smooth performance for productivity. Rich connectivity includes dual USB-C (DisplayPort + charging), USB-A, HDMI, RJ45 LAN, microSD slot, headphone jack, Wi-Fi 6, Bluetooth 5.2.",
  image:"/Image/Laptop_iamge/laptop_8_samsung.jpg",
  old_price:95599,
  new_price:87599,
  },
  {
  title: "Redmi Pad SE 4G",
  description:"Immersive 8.7″ HD+ (800x1,340) IPS LCD display with a 90 Hz refresh rate, TÜV-certified low-blue-light and flicker-free, and up to 600-nits brightness for crisp visuals. Runs on MediaTek Helio G85 octa-core chipset, paired with 4-GB RAM and 64 / 128 GB eMMC storage expandable via micro-SD (up to 2 TB). Stereo speakers with Dolby Atmos, 3.5 mm headphone jack, dual SIM 4G calling support, plus FM radio and USB-C ensures versatile connectivity .",
  image:"/Image/Tablet_img/tab_5.jpg",
  old_price:25599,
  new_price:19599,
  },
  {
  title: "Smart Washing Machine",
  description:"A Smart Washing Machine offers intelligent cleaning with Wi-Fi connectivity and app control for remote operation. It features automatic load sensing, fabric-specific wash cycles, and energy-efficient performance. Voice assistant support (Alexa/Google) adds hands-free convenience. Built-in diagnostics help troubleshoot issues without technician visits. With sleek design and smart automation, it simplifies laundry like never before.",
  image:"/Image/washing_img/ws_4.jpg",
  old_price:21599,
  new_price:13599,
  },
  {
  title: "MIVI Bluetooth Speaker",
  description:"Compact, pocket-sized cylindrical design (~164 g) with a carry-cord and available in lively colors—easy to transport and stylish for everyday use . Equipped with a robust 52 mm driver and dual passive radiators, it delivers surprisingly deep bass and crisp “studio-grade” sound at 5 W output . Features Bluetooth 5.0 for reliable connectivity within a 10 m range and includes an in-built mic for hands-free calling ." ,
  image:"/Image/speaker_image/speaker_6_mivi.jpg",
  old_price:4099,
  new_price:3299,
  },
  {
  title: "Reliance Smart android T.V",
  description:"Frameless edge-to-edge LED display (24″-43″) offering HD or Ful-HD clarity with wide 178° viewing angles for immersive visuals. Powered by Android 12 (or Google TV on newer models) with 1-1.5 GB RAM and 8 GB storage, giving you access to 5,000+ apps, seamless Chromecast, voice search, and Google Assistant. Full connectivity—dual/tri HDMI, multiple USB ports, Wi-Fi, Bluetooth—and conveniences like screen mirroring and Ethernet support" ,
  image:"/Image/TV_image/tv_7_reliance.jpg",
  old_price:24999,
  new_price:21599,
  },
];
module.exports = { data: my_data };