const more_data = [
    // Laptop Section
    {
    title: "DELL 15 Intel Core i5 12th Gen",
    description:"Stay connected to the digital world with the DELL Vostro 3520 39.62 cm (15.6) Laptop ideal for both students and working professionals. Featuring a wide display (120 Hz/250Nits) with three-sided narrow bezels,this laptop provides a smooth and enjoyable user experience. With Dell ComfortView low blue light technology, it minimises eye strain and the antiglare FHD display further enhances the visual experience, This laptop comes with Lift hinge which gives a comfortable typing angle and improved air circulation under your device, so you can work longer on your laptop comfortabily.",
    image:"/Image/Laptop_iamge/laptop_1_dell.jpg",
    old_price: 62449,
    new_price: 46990,
    },
    {
    title: "New DELL 15 Intel Core i3 10th Gen",
    description: "Stay connected to the digital world with the DELL Vostro 3520 39.62 cm (15.6) Laptop ideal for both students and working professionals. Featuring a wide display (120 Hz/250Nits) with three-sided narrow bezels,this laptop provides a smooth and enjoyable user experience. With Dell ComfortView low blue light technology, it minimises eye strain and the antiglare FHD display further enhances the visual experience, This laptop comes with Lift hinge which gives a comfortable typing angle and improved air circulation under your device, so you can work longer on your laptop comfortabily.",
    image: "/Image/Laptop_iamge/laptop_2.jpg",
    old_price: 52449,
    new_price: 34599,
    },
    {
    title: "HP 15s AMD Ryzen 3 Quad Core 5300U",
    description: "You can complete your tasks rapidly with the HP 15s Laptop. Owing to its high resolution and sophisticated display of colours, this laptop delivers an immersive and authentic viewing experience with up to 2 million pixels. In addition, thanks to its AMD processors and graphics card, this laptop allows you to get your work done quickly, thereby saving time. Also, you can browse through various applications, effortlessly do your work, make music, and more with this laptop.",
    image: "/Image/Laptop_iamge/laptop_3_hp.jpg",
    old_price: 48449,
    new_price: 33599,
    },
    {
    title: "Lenovo Chromebook MediaTek Kompanio 520",
    description: "This Lenovo Chromebook laptop comes with a 35.56 cm (14) FHD display to deliver visuals with exceptional clarity. Its 180-degree hinge allows you to share the screen with others to pitch in for brainstorming sessions. This lightweight laptop weighs about 1.4 kg making it convenient for carrying while travelling. With a long-lasting battery life of up to 10 hours, this laptop enables you to work productively without having to plug in frequently. It also comes with numerous connectivity options to connect external devices to enhance your performance.",
    image: "/Image/Laptop_iamge/laptop_4_lenvo.jpg",
    old_price: 28599,
    new_price: 17599,
    },
    {
    title: "ASUS Vivobook 15 Intel Core i3 13th Gen 1315U",
    description: "ASUS Vivobook 15 is a fashion-forward, lightweight laptop driven by up to 12th Gen Intel U-Series processors, speedy memory, and WiFi 6E. It has a stunning FHD screen, rapid charging, immersive Dirac audio, and a satisfying ErgoSense keyboard. With a privacy webcam cover, antimicrobial treatment, AI noise cancellation, and military-grade toughness, it's designed for day-to-day productivity, crisp video calls, and safe use at home, school, or on the move.",
    image: "/Image/Laptop_iamge/laptop_5_Asus.jpg",
    old_price: 54599,
    new_price: 33599,
    },
    {
    title: "AApple MacBook Air Intel Core i3 10th Gen",
    description: "The i3 Apple MacBook Air is here to fill your world with colour and immersive visuals, thanks to the Retina Display with True Tone technology. You can also be your productive best with this device as it's equipped with a Magic Keyboard, fast processor, fast graphics processor, long-lasting battery, and more. Also, this device is quite easy on the eyes. So, you can enjoy the best of both worlds. ",
    image: "/Image/Laptop_iamge/laptop_6_apple.jpg",
    old_price: 120999,
    new_price: 92549,
    },
    {
    title: "MSI Modern 15 Intel Core i3 12th Gen Core i3 1215U",
    description: "Power your passion with performance that keeps up with your dynamic lifestyle. Whether you are exploring campus life or pursuing your career, the Modern series, powered by an Intel Core i3 Mobile Processor, brings you the responsiveness and longer battery life you need to make your dreams a breathtaking reality.",
    image: "/Image/Laptop_iamge/laptop_7_msi.jpg",
    old_price: 52499,
    new_price: 34599,
    },
    // Phone data
    {
    title: "OnePlus Nord CE4 lite 5G (SUPER SILVER, 128 GB)  (8 GB RAM)",
    description: "Camera: 50 MP Main Camera with EIS; 2MP Depth-Assist Lens and 2MP Macro Lens; Front (Selfie) Camera: 16MP Rear Camera Mode: Hi-res 50 MP mode, 3x Lossles Zoom, Photo, Video, Nightscape, Expert, Panoramic, Portrait, Macro, Time-lapse, Slow-motion, Long exposure, Dual-view video, Text Scanner, 1080p/720p@30fps, Video zoom: 1080P@30fps, 720P@30fps, Slow motion: 720P@120fps, Time-Lapse: 1080P@30fps, Steady Video EIS support Display: 6.72 Inches; 120 Hz Adaptive refresh rate; FHD+(1080x2400), Colors: 16.7 Million colors, 391 ppi, Aspect Ratio: 20:9, Brightness: 550 nits (typical), 680 nits (HBM) Operating System: Oxygen OS based on Android 13.1 Processor: Qualcomm Snapdragon 695 5G Battery & Charging: 5500 mAh with 80W SUPERVOOC Endurance Edition",
    image: "/Image/Phone_image/image_3_OnePlus.jpg",
    old_price: 25599,
    new_price: 16599,
    },
    {
    title: "Samsung Galaxy A35 5G (Awesome Navy, 128 GB)  (8 GB RAM)",
    description: "The Samsung Galaxy A35 5G is a sleek blend of style and performance. Its stunning design, featuring Corning Gorilla Glass Victus+, and linear camera layout, sets it apart. Capture life's moments with the 50 MP wide-angle camera, even in low light, thanks to enhanced sensors. Record steady videos with Super HDR, OIS, and VDIS. Protect your data with Samsung Knox Vault, while enjoying the vibrant 16.83 cm FHD+ Super AMOLED display. Experience seamless multitasking with the improved GPU and NPU, and store all your content with a large internal storage. Stay connected longer with the 5000mAh battery and IP67-rated protection against spills and dust. Enjoy up to 5 years of security updates and easy data transfer with Smart Switch and Quick Share. With One UI 6, personalise your experience effortlessly. The Samsung Galaxy A35 5G: where style meets substance in a compact package.",
    image: "/Image/Phone_image/image_4_samsung.jpg",
    old_price: 31599,
    new_price: 19999,
    },
    {
    title: "Apple iPhone 16 (Black, 256 GB)",
    description: "iPhone 16. Built for Apple Intelligence. Featuring Camera Control. 48 MP Fusion camera. Five vibrant colours. And A18 chip.",
    image: "/Image/Phone_image/image_2_iPhone.jpg",
    old_price: 120999,
    new_price: 81999,
    },
    {
    title: "MOTOROLA g35 5G (Midnight Black, 128 GB)  (4 GB RAM)",
    description: "The moto g35 5G has been officially declared the fastest 5G phone under Rs. 13,000 by TechArc. Experience the fastest 5G in its segment, powered by advanced technology like 4 Carrier Aggregation (combining multiple network channels for faster speeds) and 4x4 MIMO. Enjoy lightning-fast downloads, seamless multitasking, and smooth streaming with support for all relevant 5G bands and network operators.",
    image: "/Image/Phone_image/image_9_moto.jpg",
    old_price: 16999,
    new_price: 9999,
    },
    {
    title: "OPPO Reno 12 5G (Matte Brown, 256 GB)  (8 GB RAM)",
    description: "",
    image: "/Image/Phone_image/image_5_oppo.jpg",
    old_price: 29999,
    new_price: 19999,
    },
    {
    title: "REDMI 13 5G (Orchid Pink, 128 GB)  (8 GB RAM)",
    description: "Chipset and Performance Powered by the Snapdragon® 4 Gen 2 AE Mobile Platform, it boasts 2X Cortex A78@ 2.3GHz and 6X Cortex A55@ 2.0GHz cores, ensuring smooth multitasking",
    image: "/Image/Phone_image/image_8_redmi.jpg",
    old_price: 18999,
    new_price: 13999,
    },
    {
    title: "POCO M6 Plus 5G (Ice Silver, 128 GB)  (6 GB RAM)",
    description: "108MP Dual Camera with 3x In-Sensor Zoom: Picture Perfection. Snap away with the Segment's only 108MP camera on a 5G phone and see your photos come to life in stunning detail! The 3x in-sensor zoom lets you capture every intricate detail from a distance, while the 13MP selfie camera ensures your self-portraits are always on point. With 7 film filters to play with, you can add a touch of vintage, drama, or fun to every shot. Get ready to turn every moment into a masterpiece!",
    image: "/Image/Phone_image/image_6_poco.jpg",
    old_price: 18999,
    new_price: 13999,
    },
    // Watch section
    {
    title: "REDMI Watch Move 1.85 Premium AmoLED Dual Core Processor Smartwatch",
    description: "Meet the Redmi Watch Move - your everyday smart companion with a vivid AMOLED display, 600 nits brightness, and a 2.5D curved design. Enjoy 14-day battery life with just 10 minutes of charging. Track 140+ sports with 97% accurate health monitoring. Navigate effortlessly with a functional crown and express yourself with 200+ watch faces, including India-inspired designs. Stay connected via Bluetooth calling and quick replies. Built for India with Hindi support and IP68 water resistance. Swap stylish, skin-friendly straps in seconds. Powered by Xiaomi HyperOS for smooth UI and smart sync. Made in India, designed to move with you.",
    image: "/Image/watch_image/watch_1.jpg",
    old_price: 2299,
    new_price: 1799,
    },
    {
    title: "Boult Drift BT Calling HD Display Smartwatch ",
    description: "Meet the Redmi Watch Move - your everyday smart companion with a vivid AMOLED display, 600 nits brightness, and a 2.5D curved design. Enjoy 14-day battery life with just 10 minutes of charging. Track 140+ sports with 97% accurate health monitoring. Navigate effortlessly with a functional crown and express yourself with 200+ watch faces, including India-inspired designs. Stay connected via Bluetooth calling and quick replies. Built for India with Hindi support and IP68 water resistance. Swap stylish, skin-friendly straps in seconds. Powered by Xiaomi HyperOS for smooth UI and smart sync. Made in India, designed to move with you.",
    image: "/Image/watch_image/watch_2.jpg",
    old_price: 2299,
    new_price: 1799,
    },
    {
    title: "Fire-Boltt Rise Bluetooth Calling Smartwatch",
    description: "Fire-Boltt Rise Industry's Largest Display Bluetooth Calling Smartwatch. This watch comes with a 1.85 inch Capacitive touch screen and a high resolution of 240*280 pixels. The watch supports Bluetooth Calling function. You can now make and receive calls from the watch. The watch has an inbuilt microphone and speaker to support the bluetooth calling function. Command your phone with built in voice assistant and get the functions done quickly. Fire-Boltt Rise Smart watch has a unique Neon UI and comes with 8 UI Styles to match your convinience. With over 123 Sports Modes this smartwatch is your go to fitness tracker to help you gain the goals. You can now look back at the last 7 days statistics for the exercise you have done.",
    image: "/Image/watch_image/watch_3.jpg",
    old_price: 2999,
    new_price: 1099,
    },
    {
    title: "Digital watch 4 Digital Watch",
    description: "Digital watch 4 Digital Watch Largest Display Bluetooth Calling Smartwatch. This watch comes with a 1.85 inch Capacitive touch screen and a high resolution of 240*280 pixels. The watch supports Bluetooth Calling function. You can now make and receive calls from the watch. The watch has an inbuilt microphone and speaker to support the bluetooth calling function. Command your phone with built in voice assistant and get the functions done quickly. Fire-Boltt Rise Smart watch has a unique Neon UI and comes with 8 UI Styles to match your convinience. With over 123 Sports Modes this smartwatch is your go to fitness tracker to help you gain the goals. You can now look back at the last 7 days statistics for the exercise you have done.",
    image: "/Image/watch_image/watch_4.jpg",
    old_price: 2599,
    new_price: 999,
    },
    {
    title: "Digital Watch - For Boys & Girls plain and simple Display",
    description: "igital Watch - For Boys & Girls plain and simple Display Bluetooth Calling Smartwatch. This watch comes with a 1.85 inch Capacitive touch screen and a high resolution of 240*280 pixels. The watch supports Bluetooth Calling function. You can now make and receive calls from the watch. The watch has an inbuilt microphone and speaker to support the bluetooth calling function. Command your phone with built in voice assistant and get the functions done quickly. Fire-Boltt Rise Smart watch has a unique Neon UI and comes with 8 UI Styles to match your convinience. With over 123 Sports Modes this smartwatch is your go to fitness tracker to help you gain the goals. You can now look back at the last 7 days statistics for the exercise you have done.",
    image: "/Image/watch_image/watch_5.jpg",
    old_price: 1199,
    new_price: 199,
    },
    {
    title: "Digital Watch - For Men 2025 Fashion sport watch",
    description: "Digital Watch - For Men 2025 Fashion sport watch Bluetooth Calling Smartwatch. This watch comes with a 1.85 inch Capacitive touch screen and a high resolution of 240*280 pixels. The watch supports Bluetooth Calling function. You can now make and receive calls from the watch. The watch has an inbuilt microphone and speaker to support the bluetooth calling function. Command your phone with built in voice assistant and get the functions done quickly. Fire-Boltt Rise Smart watch has a unique Neon UI and comes with 8 UI Styles to match your convinience. With over 123 Sports Modes this smartwatch is your go to fitness tracker to help you gain the goals. You can now look back at the last 7 days statistics for the exercise you have done.",
    image: "/Image/watch_image/watch_6.jpg",
    old_price: 1199,
    new_price: 199,
    },
    {
    title: "Digital Watch",
    description: "Digital Watch - For Men 2025 Fashion sport watch Bluetooth Calling Smartwatch. This watch comes with a 1.85 inch Capacitive touch screen and a high resolution of 240*280 pixels. The watch supports Bluetooth Calling function. You can now make and receive calls from the watch. The watch has an inbuilt microphone and speaker to support the bluetooth calling function. Command your phone with built in voice assistant and get the functions done quickly. Fire-Boltt Rise Smart watch has a unique Neon UI and comes with 8 UI Styles to match your convinience. With over 123 Sports Modes this smartwatch is your go to fitness tracker to help you gain the goals. You can now look back at the last 7 days statistics for the exercise you have done.",
    image: "/Image/watch_image/watch_7.jpg",
    old_price: 299,
    new_price: 99,
    },
    // T.V section
    {
    title: "XIAOMI by Mi A Series 108 cm (43 inch) Full HD LED Smart Google TV",
    description: "Presenting the Xiaomi TV, built for the ultimate in entertainment. With a stylish metal frame, its bezel-less, high-end design provides full-screen viewing. Savour-rich, 20W Dolby Audio that enhances every moment. Access movies, series, and live TV that are curated just for you across all of your applications and subscriptions with Google TV. More than 150 free live TV channels are available on Xiaomi TV+; no membership is required. It guarantees seamless performance with a Quad Core A35 CPU, 8GB of storage, and 1.5GB of RAM. With its Quick Mute, Quick Wake, and Quick Settings functions, the Xiaomi Remote enhances convenience. Enjoy entertainment to a whole new level with the Xiaomi TV, which combines style and innovation.",
    image: "/Image/TV_image/tv_1_mi.jpg",
    old_price: 31499,
    new_price: 21499,
    },
    {
    title: "Samsung 80 cm (32 inch) HD Ready LED Smart Tizen TV ",
    description: "Explore rich, immersive entertainment on the Samsung Smart TV. PurColor and HDR bring out colors in depth and contrast. Contrast Enhancer brings depth to every frame. Samsung Knox secures your devices and data. Experience hands-free control with Bixby or Alexa. Savor free content streaming on Samsung TV Plus with Tizen OS. OTS Lite and Adaptive Sound provide engaging sound, and Q-Symphony synchronizes TV and soundbar for an enhanced sound experience.",
    image: "/Image/TV_image/tv_2_samsung.jpg",
    old_price: 17990,
    new_price: 11990,
    },
    {
    title: "XIAOMI by Mi 4X 125.7 cm (50 inch) Ultra HD (4K) LED Smart Android TV  ",
    description: "This Mi TV ensures that you watch your favourite content in visuals that look life-like, clear, and rich. It comes with a 4K Display Panel which ensures the same. Also, you can watch different types of content from more than 20+ video streaming platforms, including Netflix, YouTube, and more. It is also equipped with Bluetooth 4.2, and a host of other connectivity options.",
    image: "/Image/TV_image/tv_3_mi.jpg",
    old_price: 42990,
    new_price: 37590,
    },
    {
    title: "LG 32LMBPTC 80 cm (32 inch) HD Ready LED Smart WebOS TV  ",
    description: "You can conveniently browse, stream, and watch content on the LG Smart LED TV. It runs on WebOS, allowing you to view your favourite TV series and movies on a variety of platforms, including Hotstar, Amazon Prime, Netflix, and others. In addition, this TV optimises colour for rich and natural-looking graphics, thanks to its powerful image processor. Furthermore, this TV enhances every scene with Active HDR, providing fine details and bright colours.",
    image: "/Image/TV_image/tv_4_lg.jpg",
    old_price: 21500,
    new_price: 14500,
    },
    {
    title: "SONY Bravia 2 163.9 cm (65 inch) Ultra HD (4K) LED Smart Google TV  (K-65S25) ",
    description: "We'll facilitate the installation and demo through authorized service engineer at your convenience. The installation will be done within 48 hours of delivery of the TV. The service engineer will install your new TV, either on wall mount or on table top. Wall mount stand can be asked for free at the time of installation. Installation and demo are provided free of cost. The engineer will also help you understand your new TV's features.The process generally covers: Wall-mounted or table-top installation, as requested. Physical check of all ports, including power and USB ports. Accessories are also checked, demonstration of features and settings, quick run-through on how to operate the TV.",
    image: "/Image/TV_image/tv_5_sony.jpg",
    old_price: 125000,
    new_price: 82890,
    },
    {
    title: "Acer I PRO Series 100.3 cm (40 inch) Full HD LED Smart Google TV ",
    description: "Acer I PRO Series 100.3 cm (40 inch) Full HD LED Smart Google TV with Android 14 (Black) | 16GB Storage | 30W Dolby Audio  (AR40FDIGU2841AT). Installation will be paid. The service engineer will install your new TV, either on the tabletop (free of cost) or on the wall mount which will be chargeable. The charges are applicable for wall mounts as, Rs.499 for 70 Inch. All additional accessories not part of the package will be charged separately. The service engineer will also help you understand your new TV's features.",
    image: "/Image/TV_image/tv_6_acer.jpg",
    old_price: 25999,
    new_price: 16999,
    },
    {
    title: "Reliance 80 cm (32 inch) HD Ready LED Smart WebOS TV ",
    description: "Transform your entertainment experience with the Reliance 32-inch Frameless HD Ready WebOS TV. Designed with a sleek, frameless display, this TV enhances your viewing experience with Full HD resolution, delivering crisp images, vibrant colors, and precise detail. It's perfect for any room in your home, bringing your favorite movies, shows, and games to life in stunning clarity. Powered by WebOS, this smart TV offers a smooth and intuitive interface, making it easy to access your favorite streaming services, apps, and channels. The Magic Remote allows for effortless navigation and voice commands, giving you full control of your entertainment at your fingertips.",
    image: "/Image/TV_image/tv_7_reliance.jpg",
    old_price: 17549,
    new_price: 12999,
    },
    //Bluetooth Speaker section 
    {
    title: "boat Stone 350 10 W Bluetooth Speaker  ",
    description: "Its time to enjoy a seamless playback experience courtesy boAt Stone 350 10W portable wireless speaker. The speaker comes equipped with 1.96 dynamic drivers for an immersive stereo experience. It supports instant wireless connectivity with Bluetooth v5.0. The speaker pumps out nonstop audio for up to 12 hours on a single full charge. Apart from the wireless connectivity it comes equipped with the provision for AUX and TF Card connectivity as well. Its a cylindrical construct and an IPX7 rated water resistance for a carefree listening time and easy portability.",
    image: "/Image/speaker_image/speaker_1_boat.jpg",
    old_price: 2199,
    new_price: 1599,
    },
    {
    title: "JBL Flip 6 with 12Hr Playtime, Customize Audio by App,IP67 Rating, Portable 30 W Bluetooth Speaker",
    description: "You can dance to the thumping beats of your favourite tracks with the JBL Flip 6 Portable Speaker. It combines high-quality design with powerful sound quality and can be positioned both vertically and horizontally. Additionally, this portable speaker is sure to complement your particular style. This speaker delivers sound with even low frequencies and midrange, thanks to its racetrack-shaped woofer. Furthermore, the tweeter's high frequencies are crisp with high clarity, delivering sharp and clear sound.",
    image: "/Image/speaker_image/speaker_2_jbl.jpg",
    old_price: 1199,
    new_price: 750,
    },
    {
    title: "ZEBRONICS Sound Feast 400, BTv5.0, 11h backup, TWS mode, AUX, mSD 60 W Bluetooth Party Speaker",
    description: "Unleash powerful sound and vibrant lights with the ZEB-Sound Feast 200, a feature-packed portable speaker for immersive audio. With 30W RMS output from dual 6.6cm drivers, experience deep bass and crystal-clear highs. Enjoy seamless connectivity with BT v5.3, USB, mSD, AUX, and FM Radio. Elevate your ambiance with RGB LED lights, while the TWS function lets you pair two speakers for a stereo effect. ",
    image: "/Image/speaker_image/speaker_3_zebronic.jpg",
    old_price: 3199,
    new_price: 2499,
    },
    {
    title: "Boult W40 with Quad Mic ENC",
    description: "Experience audio like never before with . Boasting an impressive 48 hours of total playtime, they ensure uninterrupted entertainment for extended periods.",
    image: "/Image/speaker_image/speaker_4.jpg",
    old_price: 1199,
    new_price: 899,
    },
    {
    title: "Portronics 1 10W TWS Portable & Type C Charging 10 W Bluetooth Speaker",
    description: "10W Bass Sound Output: Portronics SoundDrum1 10W portable Bluetooth speaker is a game changer for all gatherings. It comes with 10W Bass Sound Output which creates great volume and can enlighten your party with great music and superb sound quality. This device is a great example for TWS or True Wireless Stereo. You can connect two speakers simultaneously. It is one device that is light weight and can be carried anywhere you want. The device has in-built FM for all the radio lovers. Portronics SoundDrum1 10W comes with 2000mAH battery capacity and it has 5 Hours of Playback time.",
    image: "/Image/speaker_image/speaker_5_portronic.jpg",
    old_price: 1399,
    new_price: 849,
    },
    {
    title: "Mivi Play 12HRS Playback, Bass Boosted,TWS Feature, IPX4 5 W Portable Bluetooth Speaker",
    description: "Meet Mivi Play, a portable and powerful Bluetooth speaker made for your personal indoor use. Movie marathons, Personal Concerts or a small get together, the Mivi Play bluetooth speaker is built to let you enjoy your favourite jams in all conditions. It packs a rechargeable lithium-ion battery of up to 12 hours, lasting longer than your party. Add a second speaker with our True Wireless Stereo feature to enter a stereo mode, and enjoy an even louder bass. With Bluetooth 5.0 and an in-built microphone, this speaker comes with the latest and advanced technology for all-round quality performance. This wireless bluetooth speaker will rock your world!",
    image: "/Image/speaker_image/speaker_6_mivi.jpg",
    old_price: 999,
    new_price: 719,
    },
   {
    title: "Portronics SoundDrum 1 12W TWS Portable & Type C Charging 10 W Bluetooth Speaker",
    description: "12W Bass Sound Output: Portronics SoundDrum1 12W portable Bluetooth speaker is a game changer for all gatherings. It comes with 12W Bass Sound Output which creates great volume and can enlighten your party with great music and superb sound quality. This device is a great example for TWS or True Wireless Stereo. You can connect two speakers simultaneously. It is one device that is light weight and can be carried anywhere you want. Portronics SoundDrum1 12W comes with 2000mAH battery capacity and it has 5 to 6 Hours of Playback time.",
    image: "/Image/speaker_image/speaker_7_portronic.jpg",
    old_price: 1499,
    new_price: 999,
    },
    // Shop by Category
    {
    image: "/Image/Circle_image/circle_laptop.png",
    },
    {
    image: "/Image/Circle_image/circle_phone.jpeg",
    },
    {
    image: "/Image/Circle_image/circle_drone.jpg",
    },
    {
    image: "/Image/Circle_image/circle_tv.jpg",
    },
    {
    image: "/Image/Circle_image/circle_watch.jpg",
    },
    {
    image: "/Image/Circle_image/circle_speaker.jpg",
    },
    {
    image: "Image/Circle_image/circle_wm.jpg",
    },
    {
    image: "/Image/Circle_image/circle_freeze.jpg",
    },
    {
    image: "/Image/Circle_image/cicle_computer.jpg",
    },
    {
    image: "/Image/Circle_image/circle_cooler.jpg",
    },
    // Drone section
   {
    title: "Swa Mi Drone WiFi Camera Remote Control Quadcopter 360 Flip Stunt Drone1 Drone",
    description: "This drone comes with Dual Cameras one is Wide Angle Lens, Dual Lights & Powerful motors. 2.It has Optical Flow function which contributes for the apparent motion of the image of scene points. 3.You can easily switch cameras & take selfies on this drone with hand gesture feature. This drone is loaded with tons of features: 4.Optical Flow, Follow Me, HD Wide Angle Lens, Hand Gesture Selfie, Camera Switching, Auto Return, Headless Mode, Roll 360° Flights, One Key take off & landing, Speed Switching, Headless Mode, Master Mode, Follow Me, Gesture Photography, Emergency Stop, & App Control. Features: 5. Easy to Install, Drone Accessory, Durable, Super Bright The bracket is easy to install and remove.",
    image: "/Image/Drone_img/drone_6.jpg",
    old_price: 3590,
    new_price: 2705,
    },
   {
    title: "BYGO GPS Drone with upto 4k HD Camera One Key Start Emergency Stop Headles mode Drone",
    description: "Takeoff & Landing: Ek button se automatic takeoff aur safe landing., Altitude Hold: Drone ek fix height par stable rahta hai bina manual control ke., Headless Mode: Beginner-friendly mode jisme drone ka direction easily control ho sakta hai., GPS Navigation (Agar available ho): Accurate positioning aur auto-return-to-home feature., Return to Home (RTH): Low battery ya signal loss hone par drone automatically wapas aa jata hai., Obstacle Avoidance Sensors jo drone ko obstacles se bachate hain., Battery Backup: 10-30 minutes ki flight time, Modular Battery: Easily replaceable battery for extended flight time., Remote Control: Long-range wireless controller ke saath precise control., Mobile App Support: Drone ka control aur live streaming app ke through.",
    image: "/Image/Drone_img//drone_3.jpg",
    old_price: 15999,
    new_price: 12999,
    },
   {
    title: "Swa Mi E88 GPS Drone Camera High Quality 1500m Long Distance Professionnel 5G1 Drone",
    description: "Selfie Gesture Mode, Set Flight Path, Motion Control, Trajectory Flight, Spin Fine Tuning, Fixed Height Control, Image Flipping, Auto Hover, Add Music, Speed Mode, Emergency Stop, HD Camera, Foldable Wings, Click Photos & Record Videos, 360 Flip Stunt, Headless Mode, One Key Take off & Landing, Direction Control, Fine Tuning, Zoom, Gravity Indication etc Battery Information: 2 x 3.7V 1800mAh Li-Po Battery (Included) ; Remote Battery: 3x1.5VAA (Not Included) Camera: Yes, Weight: 380gm, Flying Height: 80-85 mtrs, Flying Time: 9-10 min, Charging Time: 40-45 min Box Contains: 1 Drone, 1 Remote Controller, 2 Drone Battery, Extra Wings & Guard, User Manual and Charging Cable Best Birthday Gift for Kids & Adults CARE INSTRUCTION: Charge atleast 40 min Before 1st Use",
    image: "/Image/Drone_img/drone_1.jpg",
    old_price: 4299,
    new_price: 2998,
    },
   {
    title: "TodFod E88 Pro Drone 4k HD foldable With Camera HD Mini 720p Live Video Drone Drone",
    description: "4K HD Camera & FPV Drone] • Upgrade 4K HD wide-angle camera with 120° angle captures high-quality video and clear aerial photos. • Enjoy real-time first-person-view on the App with FPV transmission up to 100m away. [ Multifunctional & Fun] • All-round functions including headless mode, altitude hold, and one-key takeoff/landing for easier operation. • Perform 360° flips and rolls, and engage circle fly mode for a more attractive flight experience. • Gesture control allows for easy selfie capture by simply raising your hand or striking a V sign. • The perfect drone toy gift for beginners. [ Trajectory Flight & Altitude Hold] • Draw a flight path on the app screen for the drone to autonomously follow along the designated route. • Auto Hovering ensures precise location and stable hovering, suitable for beginners and photographers. [ Easy to Use] •",
    image: "/Image/Drone_img/drone_2.jpg",
    old_price: 2599,
    new_price: 1918,
    },
   {
    title: "MASOORI Camera Waterproof Professional Drone With 4K Camera Rotation 3 Smart Batteries Drone",
    description: "Frequency: 2.4G Channel: 4CH Motor: 816 Coreless Motor Quadcopter Battery: 3.7V 1800mAh Lipo (Included) Transmitter Battery: 3x 1.5 AA Battery Flying time: 10-30 mins(Approx) Charging time: 100mins R/C Distance: 100m Color: Black Dual Camera: 1080P / 4K Quad's Size: 25*20*5.5 CM (the arms not folded) 12.5*8*5.5 CM (the arms folded) Function: Up/down, Forward/backward, Turn left/right, Sideward flight, 3-level flight speed, LED Light, Headless Mode, One Key Automatic Return, Altitude Hold Mode, WiFi FPV, Trajectory Flight, Feature: -Trajectory Flight. Draw a flight way on the screen, and the drone would conduct an autonomous flight along the designated way.",
    image: "/Image/Drone_img/drone_3.jpg",
    old_price: 15999,
    new_price: 12999,
    },
   {
    title: "RECTITUDE New Sale E88 Remote Control Drone Dual Camera Drone 720p Video, Wifi Fpv Drone",
    description: "4K HD Camera & FPV Drone] • Upgrade 4K HD wide-angle camera with 120° angle captures high-quality video and clear aerial photos. • Enjoy real-time first-person-view on the App with FPV transmission up to 100m away. [ Multifunctional & Fun] • All-round functions including headless mode, altitude hold, and one-key takeoff/landing for easier operation. • Perform 360° flips and rolls, and engage circle fly mode for a more attractive flight experience. • Gesture control allows for easy selfie capture by simply raising your hand or striking a V sign. • The perfect drone toy gift for beginners. [ Trajectory Flight & Altitude Hold] • Draw a flight path on the app screen for the drone to autonomously follow along the designated route. ",
    image: "/Image/Drone_img/drone_5.jpg",
    old_price: 2549,
    new_price: 1838,
    },
    // cooler section
   {
    title: "BAJAJ 36 L Room/Personal Air Cooler  (White, PX97 Torque New)",
    description: "You can stay cool and comfortable at all times with the Bajaj 36 L Room Personal Air Cooler. It provides up to three speed options to adjust the airflow as per your requirements. This allows you to customise the cooling experience based on the temperature and humidity levels in your room for optimal comfort. Additionally, this air cooler is portable and lightweight, making it easy to move between rooms. Moreover, this air cooler features honeycomb cooling pads, providing efficient and long-lasting cooling for a refreshing and comfortable experience. ",
    image: "/Image/Circle_image/circle_cooler.jpg",
    old_price: 8549,
    new_price: 5749,
    },
   {
    title: "Kenstar 45 L Room/Personal Air Cooler  (WHITE, BLUE, TURBOCOOL NEO HC 45)",
    description: "Kenstar Turbocool Neo 45 Personal Cooler",
    image: "/Image/Cooler_img/cooler_1.jpg",
    old_price: 9999,
    new_price: 6199,
    },
   {
    title: "Thomson 115 L Desert Air Cooler  (Grey, 115 L Desert Air Cooler (Grey, HD115))",
    description: "This Thomson Air Cooler boasts energy efficiency and durability in its Double Ball Bearing Motor and alloy metal blade for long quiet operation. Its high-tech cooling medium offers a natural breeze, and the water level indicator for easy running ensures continuous use. With castor wheels for easy mobility and inverter compatibility, this cooler offers continuous comfort even during a power outage, making it ideal for a comfortable and hassle-free home.",
    image: "/Image/Cooler_img/cooler_2.jpg",
    old_price: 25999,
    new_price: 11599,
    },
   {
    title: "Voltas 92 L Desert Air Cooler  (White, GRAND-92 With Turbo Air Throw Technology)",
    description: "Volta's Desert Cooler Range are designed for large areas and higher cooling needs. Equipped with large water storage capacity and capable of strong air flow required to maximize cooling in the harshest of summers. It can be used in homes as well as offices, banquet halls etc and work efficiently for long operational hours. The Honeycomb cooling pad cools the air passing through it without any water retention.",
    image: "/Image/Cooler_img/cooler_4.jpg",
    old_price: 17999,
    new_price: 11990,
    },
   {
    title: "Symphony 95 L Desert Air Cooler  (White, JUMBO 95 XL +)",
    description: "The Symphony air cooler is equipped with numerous features for you to stay comfortable during extreme weather conditions. It features a powerful blower along with a cool flow dispenser to provide effective cooling uniformly. This inverter-compatible cooler works well with inverters so you can enjoy uninterrupted cooling even when the power is out. Its auto-louvre movement feature delivers cool air to every corner of your room. It also features a drain plug, water overflow outlet, water level indicator, and much more to provide enhanced convenience.",
    image: "/Image/Cooler_img/cooler_5.jpg",
    old_price: 17999,
    new_price: 11990,
    },
    // Washing Machine section
   {
    title: "Voltas Beko 9 kg Semi Automatic Top Load Washing Machine ",
    description: "This Voltas Beko washing machine can easily meet up to your day-to-day laundry needs. It comes with an IPX4-rated display panel that is water resistant, letting you keep track of operation despite any spills. It also comes with a soft-closing door to protect your fingers from accidental damage. The machine also comes with a Magic filter that helps trap all the lint, fluff, and other particles stuck to clothes, thus giving your clothes a clean and hygienic wash.",
    image: "/Image/washing_img/ws_5.jpg",
    old_price: 16599,
    new_price: 12190,
    },
   {
    title: "MarQ by Flipkart 6.5 kg 5 Star Rating Innowash Range Semi Automatic Top Load Washing Machine ",
    description: "The MarQ by Flipkart semi-automatic top-load washing machine series exemplifies durability and high energy efficiency, designed with Indian conditions in mind. Equipped with an intelligent turbo wash program and a 1350 RPM Pulsator motor, it offers an air-dry lid with a 360-degree rotational wash, deep detergent penetration, collar scrubbing, and effective germ elimination, resulting in clothes that are as good as new.",
    image: "/Image/washing_img/ws_1.jpg",
    old_price: 16599,
    new_price: 12190,
    },
   {
    title: "Voltas Beko 6.5 kg Semi Automatic Top Load Washing Machine",
    description: "The Voltas Beko semi-automatic top-load washing machine is designed to make your laundry needs easy and efficient. With the special pulsator wash technology, this washing machine creates strong water flow to offer a powerful wash cycle without damaging your clothes. The air drying feature of this washing machine ensures quick drying of your clothes, thereby reducing energy consumption. It comes with a lint filter to collect all tiny particles during the wash cycle and keeps your clothes spotless. With the IPX4-protected control panel of this washing machine, you do not have to worry about water splashes damaging your machine.",
    image: "/Image/washing_img/ws_3.jpg",
    old_price: 16599,
    new_price: 12190,
    },
   {
    title: "LG 7 kg 5 Star with Wind Jet Dry, Collar Scrubber and Rust Free Plastic Base Semi Automatic Top Load Washing Machine ",
    description: "You can effortlessly wash your clothes with the LG P7020NGAZ 7 kg Washing Machine. With its Rat Away technology, this washing machine boasts a 3 mm thick sturdy plastic base that is coated with a rat repellent chemical that helps prevent damage, increasing its durability and performance. In addition, thanks to its Wind Jet Dry function, this washing machine dries the laundry and the interior by spinning at high speeds to remove moisture from your clothes.",
    image: "/Image/washing_img/ws_2.jpg",
    old_price: 15499,
    new_price: 10970,
    },
   {
    title: "LG 8 kg 5 Star, AI Direct Drive Technology, Steam, 6 Motion DD Fully Automatic Front Load Washing Machine",
    description: "This LG 8 kg Fully Automatic Front Load Washing Machine includes a novel AI Direct Drive technology that attempts to give your clothes a perfect wash by recognising not only the weight of the load but also sensing the softness of the fabric, using data from over 20,000 wash patterns for a variety of laundry. This enables the washing machine to select the best motion for a wonderful wash.",
    image: "/Image/washing_img/ws_4.jpg",
    old_price: 42499,
    new_price: 35900,
    },
   {
    title: "Apple iPhone 15",
    description: "The Apple iPhone is a sleek, high-performance smartphone known for its premium design and user-friendly interface. It runs on iOS, offering seamless integration with other Apple devices and services. iPhones feature powerful processors, advanced camera systems, and cutting-edge security like Face ID. They support a vast ecosystem of apps, making them ideal for work, entertainment, and creativity. With regular software updates, Apple ensures long-term performance and enhanced user experience.",
    image: "/Image/Phone_image/image_1_iPhone.jpg",
    old_price: 135000,
    new_price: 120000,
    },
   {
    title: "ZEBRONICS Zeb- Thunder, With 60H Backup, BT v5.3, Gaming Mode, ENC, AUX, mSD, Dual Pairing Bluetooth",
    description: "If you are fond of headphones that come in exciting colours to match your outfit, then opt for the ZEB-Thunder headphones launched in 4 different vibrant colour combinations. mmerse yourself in the ultimate gaming adventure with the Zeb-Thunder headphones, ensuring a lag-free experience. With a built-in rechargeable battery, these headphones provide an astounding 60 hours(at 50% volume) of continuous play, keeping the fun going for longer periods.",
    image: "/Image/Headphone/head_1_zebronic.jpg",
    old_price: 1599,
    new_price: 799,
    },
   {
    title: "OnePlus Nord Buds 3 with up to 32dB ANC Bluetooth ",
    description: "OnePlus Nord Buds 3 support all the smartphones.",
    image: "/Image/Headphone/head_2_OnePlus.jpg",
    old_price: 3599,
    new_price: 2299,
    },
   {
    title: "DELL AIO Inspiron 5430 Core i3 (8 GB DDR4/512 GB SSD/Windows 11 Home/23.8 Inch Screen/AIO Inspiron 5430)",
    description: "OnePlus Nord Buds 3 support all the smartphones.",
    image: "/Image/Computer_img/computer_1_dell.jpg",
    old_price: 70599,
    new_price: 66513,
    },
   {
    title: "Nothing Phone (3a) (Black, 256 GB)  (8 GB RAM)",
    description: "Replay life's best bits again and again with the Phone (3a)'s camera system that consistently delivers true-to-life results. Captures every light and shadow in stunning detail for elite-level shots, wherever you are. Boasting a large, light-absorbing 50 MP sensor with the largest full well capacity in its class, a high-res 50 MP telephoto sensor with up to 30X ultra zoom, a 32 MP front camera for superstar groufies, and a 120º ultra-wide field of view. All four sensors support Ultra HDR photo output.",
    image: "/Image/Phone_image/image_11_nothing.jpg",
    old_price: 31599,
    new_price: 26599,
    },
   {
    title: "Samsung Galaxy Book4 Intel Core 5 120U - (8 GB/512 GB SSD/Windows 11 Home) ",
    description: "Conquer your day with the latest Intel Core processor and integrated Intel graphics, delivering super-smooth performance for streaming and seamless multitasking. Galaxy Book4 is encased in a full metal body that weighs just 1.55 kg, so it's sleek, compact and ready to go. And with a large 39.62 cm Full HD display, you can enjoy a crisp and vibrant picture onscreen while you unwind with your favorite clips and flicks. The AI-powered Photo Remaster tool brings new life into old photos and low-quality images. The feature allows you to clean up blurry photos, remove unwanted light and shade with just a tap.",
    image: "/Image/Laptop_iamge/laptop_8_samsung.jpg",
    old_price: 75999,
    new_price: 67990,
   },
   {
    title: "Acer Aspire 7 Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 2050)",
    description: "The Acer Aspire 7 gaming laptop combines powerful performance with sleek portability. Equipped with an NVIDIA GeForce RTX 2050, it delivers stunning graphics for immersive gameplay. Its 8GB DDR4 RAM and 512 GB PCIe SSD ensure fast load times and ample storage. The 39.62 cm (15.6) FHD display with a 144 Hz refresh rate offers crisp, fluid visuals, while the RGB backlit keyboard adds a customisable style to your setup. With Intel Wi-Fi 6 and Bluetooth 5.2, enjoy seamless connectivity. Weighing less than 2 kg, the Acer Aspire 7 is perfect for gaming on the go.",
    image: "/Image/Laptop_iamge/laptop_9_Aspire.jpg",
    old_price: 65999,
    new_price: 54990,
   },
   {
    title: "vivo T4x 5G (Pronto Purple, 128 GB)  (6 GB RAM)",
    description: "Go All Day , Every Day with no limits with vivo T4x 5G. The 6500 mAh battery and 44W FlashCharge deliver all-day energy, quick recharges, and smart efficiency for nonstop use.",
    image: "/Image/Phone_image/image_7_vivo.jpg",
    old_price: 17999,
    new_price: 13999,
   },
   {
    title: "HP AIO 27-cr0407in Core i5 (16 GB DDR4/Windows 11 Home/27 Inch Screen/27-cr0407in)  (White)",
    description: "Go All Day , Every Day with no limits with vivo T4x 5G. The 6500 mAh battery and 44W FlashCharge deliver all-day energy, quick recharges, and smart efficiency for nonstop use.",
    image: "/Image/Computer_img/computer_2_hp.jpg",
    old_price: 85599,
    new_price: 79500,
   },
   {
    title: "ZEBRONICS ZEB JUMBO LITE Bluetooth  (Black, In the Ear)",
    description: "Model name ZEB-YOGA 7 BT Version 5.2 Supported BT Profile HSP / SPP / AVRCP / A2DP Drive Size 14.2mm Speaker Impedance 32? Playback Time 70h* Charging Time 2h Talk Time 48-50h Standby Time 500h Package Dimension (W x D x H) 193.5 x 27.5 x 231.6 mm Net Weight 42g Country of Origin India * at 50% Volume Package Contents Neckband 1 U Eartips 4 U Charging Cable 1 U QR code guide 1 U",
    image: "/Image/Headphone/head_3_zebronic.jpg",
    old_price: 1749,
    new_price: 1449,
   },
   {
    title: "IQOO Z10X 5G (Ultramarine, 256 GB)  (8 GB RAM)",
    description: "IQOO Z10X 5G (Ultramarine, 256 GB)  (8 GB RAM) |India's Biggest Ever 7300 mAh Battery | Snapdragon 7s Gen 3 Processor | Brightest Quad Curved AMOLED Display in The Segment",
    image: "/Image/Phone_image/image_10_iQOO.jpg",
    old_price: 21999,
    new_price: 16900,
   },
   {
    title: "HP MSO 2024 Intel Core i5 13th Gen 1334U - (16 GB/512 GB SSD/Windows 11 Home) ",
    description: "This HP fd0467TU laptop enables rapid computing because of the 13th Gen Intel Core i5-1334U processor with 12 threads and 10 cores. This laptop supports 512 GB PCIe SSD wherein you can access your data easily with 16 GB DDR4-3200 MT/s RAM. Additionally, this laptop has a 15.6 FHD display, consisting of 250 nits brightness, micro-edge bezels, and an Anti-glare screen. Furthermore, this laptop is equipped with an integrated numeric keyboard and HP Imagepad. Plus, this laptop offers seamless connectivity, a 41 Wh battery, and an eco-friendly design.",
    image: "/Image/Laptop_iamge/laptop_10_hp.jpg",
    old_price: 65599,
    new_price: 53990,
   },
   {
    title: "ASUS V400 AiO Series, All in One Desktop, 13th Gen Intel Core i3 (8 GB DDR5/512 GB SSD/Windows 11 Home/23.8 Inch Screen/V440VAB-KBPC002WS)",
    description: "The ASUS V400 AiO is a sleek, powerful all-in-one PC with a 93% screen-to-body ratio, 100% sRGB color accuracy, and 178° wide-view. It features 13th Gen Intel Core processor, DDR5 memory, Wi-Fi6E , Dolby® Atmos, and AI-powered noise-canceling technology for an immersive experience.",
    image: "/Image/Computer_img/computer_3_Asus.jpg",
    old_price: 51599,
    new_price: 42490,
   },
   {
    title: "ZEBRONICS Zeb-Jet Pro Premium Headphone,LED Headband",
    description: "Driver Size 40mm Speaker Impedance 32? Frequency Response 20Hz-20kHz Sensitivity 120dB ± 3dB Microphone Impedance 32? Microphone Sensitivity -38dB±3dB Connector type 3.5mm + USB (for lights) Cable length 2 Meters Package Dimension (W x D x H) 202 x 114 x 225 mm Net. Weight 283g Country of Origin Peoples Republic of China Package Contents Headphone 1 U.",
    image: "/Image/Headphone/head_5_zebroinc.jpg",
    old_price: 1599,
    new_price: 1199,
   },
   {
    title: "Samsung Galaxy Tab A9+ 8 GB RAM 128 GB ROM 11.0 inch with Wi-Fi+5G Tablet (Graphite)",
    description: "DN",
    image: "/Image/Tablet_img/tab_1_samsung.jpg",
    old_price: 35599,
    new_price: 32599,
   },
   {
    title: "realme Pad 2 Lite 4 GB RAM 128 GB ROM 10.95 inch with 4G Tablet (Nebula Purple)",
    description: "Experience entertainment like never before with the realme Pad 2 Lite. Featuring a stunning 2K Eye Comfort Display for vibrant visuals and a robust Mediatek Helio G99 Chipset for seamless multitasking, this tablet is designed for immersive experiences. Its 8300mAh battery ensures hours of uninterrupted use, while quad stereo speakers with OReality Audio provide rich sound. With an ultra-slim design and 4G connectivity, the realme Pad 2 Lite is your stylish companion for entertainment on the go.",
    image: "/Image/Tablet_img/tab_2.jpg",
    old_price: 19599,
    new_price: 14999,
   },
   {
    title: "OnePlus Pad Go 8 GB RAM 128 GB ROM 11.35 inch with Wi-Fi Only Tablet (Twin Mint)",
    description: "NA",
    image: "/Image/Tablet_img/tab_3.jpg",
    old_price: 21599,
    new_price: 17999,
   },
   {
    title: "boAt 450 Pro with Upto 70 Hours Playback Bluetooth ",
    description: "boAt Rockerz 450 Pro is a power-packed on-ear wireless headphone that has been ergonomically designed to meet the needs of music lovers. The headphones come equipped with Bluetooth V5.0 for instant wireless connectivity. Apart from the wireless connectivity, one can utilize the AUX cable as well for a wired playback experience. Though we reckon that it will rarely come into use cause of the headphone super powerful 750mAh battery: it provides a humongous playtime of up to 70 hours! Its 40mm drivers help supply superior musical experience to the user with immersive sound. With our ASAP fast charge technology, you can get up to 10 hours of playback in just 10 minutes of charge. ",
    image: "/Image/Headphone/head_6_boat.jpg",
    old_price: 2199,
    new_price: 1799,
   },
   {
    title: "Apple iMac Core i5 (5th Gen) (8 GB DDR3/1 TB/Mac OS X Sierra/21.5 Inch Screen/MK482HN/A)",
    description: "Accessibility Features: VoiceOver, Reduce Motion, Text to Speech, Siri and Dictation, Switch Control, Increase Contrast, Operating Temperature: 10 Degree C to 35 Degree C, Relative Humidity: 5% to 95% Non-condensing.",
    image: "/Image/Computer_img/computer_4_apple.jpg",
    old_price: 105999,
    new_price: 91490,
   },
   {
    title: "REDMI Pad SE 4G 4 GB RAM 64 GB ROM 8.7 Inch with 4G Tablet (Urban Grey)",
    description: "4G+4G Calling With 2+1 Slot 2. 90Hz Refresh Rate 3. Dual Speakers With Dolby® Atmos 4. Large 6650mAh(typ) Battery",
    image: "/Image/Tablet_img/tab_5.jpg",
    old_price: 13999,
    new_price: 9999,
   },
   {
    title: "Acer 60.45 cm (23.8 inch) Full HD LED Backlit IPS Panel Monitor (V247Y E)",
    description: "High reliability with outstanding performance Seeing more of what matters most with a near bezel-less display, the V247Y enhances your professional needs with its robust stand and wide range of color-enhancing technologies. V247Y also feature the Acer Display Widget utility software & navigation OSD key design, letting you easily modify monitor settings with flexibility. Designed for the work professional, the V247Y IPS Monitor features a small bezel surrounding a 1920 x 1080 display. In addition to the Full HD resolution, this monitor also features a 4 ms response time and support for up to 16.7 million colors as well as AMD Adaptive-Sync functionality.",
    image: "/Image/Computer_img/computer_5_acer.jpg",
    old_price: 11999,
    new_price: 7280,
   },
   {
    title: "Apple 2025 iPad Air (M3) 128 GB ROM 11.0 inch with Wi-Fi Only (Blue)",
    description: "Rear Camera: 12MP Wide Camera (f/1.8 Aperture, Digital Zoom Upto 5x, Five Element Lens, Panorama (Upto 63MP), Sapphire Crystal Lens Cover, Autofocus with Focus Pixels, Smart HDR 4, Wide Colour Capture for Photos and Live Photos, Photo Geotagging, Auto Image Stabilisation, Burst Mode, Image Formats Captured: HEIF and JPEG) | Front Camera: Landscape 12MP Center Stage Camera (f/2.0 Aperture, Smart HDR 4, 1080p HD Video Recording at 25 fps, 30 fps or 60 fps, Timelapse Video with Stabilisation, Extended Dynamic Range for Video Upto 30 fps, Cinematic Video Stabilisation (1080p and 720p), Wide Colour Capture for Photos and Live Photos, Lens Correction, Retina Flash with True Tone, Auto Image Stabilisation, Burst Mode).",
    image: "/Image/Tablet_img/tab_6.jpg",
    old_price: 65999,
    new_price: 59900,
   },
];

module.exports = { data: more_data };